services:
  buildkite-agent:
    image: buildkite/agent:3
    depends_on:
      - chinmina-bridge
    command: [ "start" ]
    environment:
      - BUILDKITE_AGENT_TOKEN
    volumes:
      - "../agent/startup:/docker-entrypoint.d:ro"
      - "../agent/hooks:/buildkite/hooks:ro"
    secrets:
      - netskope

  chinmina-bridge:
    image: alpine
    depends_on:
      - jaeger
    working_dir: "/src"
    command: [ "./dist/chinmina-bridge" ]
    environment:
      - ENV=development
      - SERVER_PORT=80
      - BUILDKITE_API_TOKEN
      - JWT_BUILDKITE_ORGANIZATION_SLUG
      - JWT_AUDIENCE=github-app-auth:jamestelfer
      - GITHUB_APP_PRIVATE_KEY
      - GITHUB_APP_ID
      - GITHUB_APP_INSTALLATION_ID
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - "..:/src"

  # jaeger all in one for local OTEL tracing, using in-memory storage which is
  # not persisted.
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686" # viewer
      - "16687:16687" # admin
    environment:
      - LOG_LEVEL=debug

secrets:
  netskope:
    environment: "NETSKOPE_CERT"
