name: Release

on:
  push:
    # version tags are protected in this repository
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    # deploy with the correct environment to allow DockerHub access
    environment: "Publish"

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v2.3.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
